---
title: Welcome to Homework 2
date: 2023-08-30
author: Cameron Lohman
format:
    gfm:
        mermaid-format: png
---

This is my solution to homework 2. I'm using Quarto render this document from a QMD file to a regular
MD file for display on GITHUB.

## Scenario

Imagine you're designing a Library Management System for a small local library. The system needs to track information about books and library members. Each book has a unique ISBN (International Standard Book Number), a title, and a publication year. Each library member is identified by a unique member ID, and the system needs to store their name and contact information. Library members can check out books, but they don’t have to.

## Design Task 1

Identify and document the entities, attributes, and relationships using Chen notation.

```{dot}
//| echo: false
graph ER {
	fontname="Helvetica,Arial,sans-serif"
	node [fontname="Helvetica,Arial,sans-serif"]
	edge [fontname="Helvetica,Arial,sans-serif"]
	layout=neato
	node [shape=box]; course; discipline; student;
	node [shape=ellipse]; {node [label="name"] name0; name1; name2;}
		code; grade; number;
	node [shape=diamond,style=filled,color=lightgrey]; "Offers"; "Enrolls"; "majors";

	name0 -- course;
	code -- course;
	course -- "Offers" [label="n",len=1.00];
	"Offers" -- discipline [label="1",len=1.00];
	discipline -- name1;
	discipline -- "majors" [label="1",len=1.00];
	"majors" -- student [label="n",len=1.00];
	student -- grade;
	student -- name2;
	student -- number;
	student -- "Enrolls" [label="m",len=1.00];
	"Enrolls" -- course [label="n",len=1.00];

	fontsize=20;
}
```

## Design Task 2

Identify and document the entities, attributes, and relationships using Crow’s Foot notation.

*(remove this block and add your your solution here!)*

